---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steamapp
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: 
  - ReadWriteMany
  resources:
    requests: 
      storage: 20Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proton
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
