---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enshrouded-dedicated-server
  namespace: {{ .Release.Namespace }}
  labels:
    name: enshrouded-dedicated-server
spec:
  replicas: 1
  serviceName: enshrouded-dedicated-server
  selector:
    matchLabels:
      name: enshrouded-dedicated-server
  template:
    metadata:
      labels:
        name: enshrouded-dedicated-server
    spec:
      containers:
      - image: quay.io/steamutils/proton-runner:latest
        name: enshrouded
        args: ["enshrouded_server.exe"]
        env:
        - name: STEAMCMD_ARGS
          value: '+@sSteamCmdForcePlatformType windows +force_install_dir /steamapp +login anonymous +app_update 2278520 -public validate +quit'
        ports:
        - name: game-port
          containerPort: {{ .Values.serverGamePort }}
          protocol: UDP
        - name: query-port
          containerPort: {{ .Values.serverQueryPort }}
          protocol: UDP
        volumeMounts:
        - name: steamapp
          mountPath: /steamapp
        - name: proton
          mountPath: /proton
        - name: savegame
          mountPath: /steamapp/savegame
        - name: logs
          mountPath: /steamapp/logs
        - name: enshrouded-server-json
          mountPath: /steamapp/enshrouded_server.json
          subPath: enshrouded_server.json
      volumes:
      - name: steamapp
        persistentVolumeClaim:
          claimName: steamapp
      - name: proton
        persistentVolumeClaim:
          claimName: proton
      - name: savegame
        persistentVolumeClaim:
          claimName: {{ if .Values.importedSave.enabled }}{{ .Values.importedSave.pvcName }}{{ else }}savegame{{ end }}
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: enshrouded-server-json
        configMap:
          name: enshrouded-server-json
          items:
          - key: enshrouded_server.json
            path: enshrouded_server.json
