apiVersion: v1
data:
  enshrouded_server.json: |
    {
            "name": "{{ .Values.serverName }}",
            "password": "{{ .Values.serverPassword }}",
            "saveDirectory": "{{ .Values.serverSaveDirectory }}",
            "logDirectory": "{{ .Values.serverLogDirectory }}",
            "ip": "0.0.0.0",
            "gamePort": {{ .Values.serverGamePort }},
            "queryPort": {{ .Values.serverQueryPort }},
            "slotCount": {{ .Values.serverSlotCount }}
    }
kind: ConfigMap
metadata:
  name: enshrouded-server-json
  namespace: {{ .Release.Namespace }}
