{{- if not .Values.importedSave.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: savegame
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
{{- end -}}
