apiVersion: v1
kind: Service
metadata:
  name: enshrouded-dedicated-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: game
    port: {{ .Values.serverGamePort }}
    nodePort: {{ .Values.serverGamePort }}
    protocol: UDP
  - name: query
    port: {{ .Values.serverQueryPort }}
    nodePort: {{ .Values.serverQueryPort }}
    protocol: UDP
  loadBalancerIP:
  type: NodePort 
  selector:
    name: enshrouded-dedicated-server
