apiVersion: v1
entries:
  enshrouded-dedicated-server:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-04-19T15:04:36.527431757-07:00"
    description: Helm chart for installing an enshrouded dedicated server
    digest: 8f33d8baeadb093f4418b49e3338744eafb74147a8c327aeff3d8dda392ef5ed
    icon: https://styles.redditmedia.com/t5_8chex6/styles/communityIcon_nvnkci2rcsqb1.png
    name: enshrouded-dedicated-server
    type: application
    urls:
    - enshrouded-dedicated-server-1.0.0.tgz
    version: 1.0.0
generated: "2024-04-19T15:04:36.527174428-07:00"
