---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steamapp-2278520
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: enshrouded-installer
        image: quay.io/steamutils/steamcmd:latest
        volumeMounts:
        - mountPath: /steamapp
          name: steamapp
        args: ["+@sSteamCmdForcePlatformType","windows","+force_install_dir","/steamapp","+login","anonymous","+app_update","2278520","-public","validate"]
      volumes:
      - name: steamapp
        persistentVolumeClaim:
          claimName: steamapp-2278520
