---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enshrouded-dedicated-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: enshrouded
        image: quay.io/steamutils/proton-runner:latest
        args: ["/steamapp/enshrouded_server.exe"]
        volumeMounts:
        - mountPath: /steamapp
          name: steamapp
        - mountPath: /proton
          name: proton
        - mountPath: /steamapp/enshrouded_server.json
          name: config
        ports:
        - name: app-udp
          containerPort: 15636
          hostPort: 15626
          protocol: UDP
        - name: query-udp
          containerPort: 15637
          hostPort: 15637
          protocol: UDP
      volumes:
      - name: steamapp
        persistentVolumeClaim:
          claimName: steamapp-2278520
      - name: proton
        persistentVolumeClaim:
          claimName: proton-2278520
      - name: config
        hostPath:
          path: ../enshrouded_server.json
          type: File
