#!/bin/bash
# Installs a Steamapp into a local volume
# This is best used for local installation, not for K8s deployments
#
# Creates Volume
podman volume exists steamapp-$STEAMCMD_APPID || podman volume create steamapp-$STEAMCMD_APPID
podman volume exists proton-$STEAMCMD_APPID || podman volume create proton-$STEAMCMD_APPID

# Run the installer
podman run -it --name steamcmd-appinstaller-$STEAMCMD_APPID \
	-e STEAMCMD_APPID=$STEAMCMD_APPID \
	-e STEAMCMD_APP_BRANCH=-$STEAMCMD_APP_BRANCH \
	-v steamapp-$STEAMCMD_APPID:/steamapp:z \
	quay.io/steamutils/steamcmd:latest \
	+@sSteamCmdForcePlatformType windows +force_install_dir /steamapp +login anonymous +app_update $STEAMCMD_APPID -$STEAMCMD_BRANCH validate +quit

# Remove leftover container
podman rm -f steamcmd-appinstaller-$STEAMCMD_APPID
